name: LTCraft
main: cn.LTCraft.core.Main
version: 1.0.0
author: Angel、
depend: [HolographicDisplays, ProtocolLib, TrMenu]
commands:
  lt:
    description: LTCraft核心命令
    permission: op
    usage: /lt
  mmskills:
    description: 释放mm技能
    permission: op
    usage: /mmskills 技能名字
  ltc:
    description: 职业管理
    permission: op
    usage: /ltc
  lte:
    description: 兑换的物品
    permission: op
    usage: /lte 需要兑换的物品
  prefix:
    description: 称号命令
    permission: true
    usage: /prefix 称号
  sign:
    description: 编辑木牌
    permission: LTCraft.sign
    usage: /sign 第一行 第二行 第三行 第四行
  clear:
    description: 清理垃圾
    permission: op
    usage: /clear [?all]
  rtp:
    description: 随机传送
    permission: LTCraft.rtp
    usage: /rtp
  cinfo:
    description: 个人信息
    permission: true
    usage: /cinfo
  ltms:
    description: MM刷怪点管理
    usage: /lts args...
    permission: op
  ltcs:
    description: 箱子刷怪点管理
    usage: /lts args...
    permission: op
  ltg:
    description: 传送门管理
    usage: /ltg args...
    permission: op
  vip:
    description: VIP管理
    usage: /vip args...
    permission: true